---
# ============================================================================
# 📊 CONEXÃO DE SORTE - JAEGER INFRAESTRUTURA
# ============================================================================
# Data de Criação: 17/09/2025 às 04:30 BRT
# Última Atualização: 17/09/2025 às 04:30 BRT
# Responsável: Sistema Automatizado
# Versão: 1.0.0
# ============================================================================
#
# JAEGER STANDALONE - Distributed Tracing
# - Docker Swarm deployment
# - Overlay encrypted network para segurança
# - Health checks otimizados para produção
# - All-in-one deployment para simplicidade
# ============================================================================

services:
  # ============================================================================
  # 📊 JAEGER - Distributed Tracing
  # ============================================================================
  jaeger:
    image: ${JAEGER_IMAGE:-jaegertracing/jaeger:2.1.0}
    hostname: conexao-jaeger
    user: "10001:10001"
    init: true
    stop_grace_period: 30s
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      MEMORY_MAX_TRACES: 5000
      JAEGER_DISABLED: "false"
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      QUERY_BASE_PATH: "/jaeger"
      # Configuração simplificada para desenvolvimento
      JAEGER_LOG_LEVEL: "info"
    networks:
      conexao-network-swarm:
        aliases:
          - conexao-jaeger
          - jaeger
    # 🚨 SECURITY: Portas removidas - acesso apenas via Traefik
    # ports:
    #   - "16686:16686"  # Jaeger UI - REMOVIDO: usar Traefik
    #   - "14268:14268"  # Jaeger Collector HTTP - REMOVIDO: interno apenas
    #   - "14269:14269"  # Jaeger Collector gRPC - REMOVIDO: interno apenas
    #   - "9411:9411"    # Zipkin compatible endpoint - REMOVIDO: interno apenas
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 200s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 300s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        monitor: 30s
        order: stop-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

    # ==========================================================================
    # 🏷️ TRAEFIK LABELS - JAEGER UI VIA TRAEFIK
    # ==========================================================================
    labels:
      # Habilitar Traefik para este serviço
      - "traefik.enable=true"
      - "traefik.docker.network=conexao-network-swarm"

      # Configuração do serviço Jaeger UI
      - "traefik.http.services.jaeger-ui.loadbalancer.server.port=16686"
      - "traefik.http.services.jaeger-ui.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.jaeger-ui.loadbalancer.healthcheck.interval=30s"

      # Roteamento do Jaeger UI (acesso restrito)
      - "traefik.http.routers.jaeger-ui.rule=Host(`monitoring.conexaodesorte.com.br`) && PathPrefix(`/jaeger`)"
      - "traefik.http.routers.jaeger-ui.entrypoints=websecure"
      - "traefik.http.routers.jaeger-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jaeger-ui.service=jaeger-ui"
      - "traefik.http.routers.jaeger-ui.middlewares=jaeger-stripprefix"

      # Acesso simplificado para desenvolvimento (sem autenticação)
      # - "traefik.http.middlewares.jaeger-auth.basicauth.usersfile=/run/secrets/JAEGER_HTPASSWD"

      # Middleware para remover prefixo /jaeger
      - "traefik.http.middlewares.jaeger-stripprefix.stripprefix.prefixes=/jaeger"

      # Configuração do serviço Jaeger Collector (interno)
      - "traefik.http.services.jaeger-collector.loadbalancer.server.port=14268"
      - "traefik.http.routers.jaeger-collector.rule=Host(`jaeger-collector.conexaodesorte.internal`)"
      - "traefik.http.routers.jaeger-collector.service=jaeger-collector"
      - "traefik.http.routers.jaeger-collector.entrypoints=web"

      # Metadata do serviço
      - "org.opencontainers.image.title=Conexão de Sorte - Jaeger Tracing"
      - "org.opencontainers.image.description=Distributed tracing e observabilidade"
      - "org.opencontainers.image.version=2.1.0"
      - "microservice.type=observability"
      - "microservice.category=monitoring"

# ============================================================================
# 🔐 CONFIGURAÇÃO SIMPLIFICADA PARA DESENVOLVIMENTO
# ============================================================================
# Secrets de autenticação removidos para compatibilidade com ambiente de desenvolvimento

# ============================================================================
# 🌐 NETWORKS EXTERNOS
# ============================================================================
networks:
  conexao-network-swarm:
    external: true
    name: conexao-network-swarm